name: Visualize cloudbuild job graph and commit
on: push

env:
  SEARCH_DIRECTORIES: sample
  FILENAME_REGEX: 'cloudbuild.*.yaml'

jobs:
  format:
    runs-on: ubuntu-20.04
    name: Visualize cloudbuild job graph and commit
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0

      - name: Create png image for each cloudbuild.yaml
        uses: gecko655/github-action-commit-visualized-gcb-graph@v0.0.1
        with:
          search-directories: '${{ env.SEARCH_DIRECTORIES }}'
          filename-regex: '${{ env.FILENAME_REGEX }}'

      - name: commit and push
        uses: EndBug/add-and-commit@v7.4.0
        with:
          message: "Visualize cloudbuild jobs by GitHub Action"
          committer_name: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
          push: true
